In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#importing dataset
dataset=pd.read_csv('data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [3]:
#check null value
dataset.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [4]:
print(y)
y=y.reshape(-1,1)
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [5]:
#spliting dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(y_test)

[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


In [6]:
#feature scaling
from sklearn.preprocessing import StandardScaler
ss_x=StandardScaler()
x_train=ss_x.fit_transform(x_train)
ss_y=StandardScaler()
y_train=ss_y.fit_transform(y_train)

In [7]:
#model training
from sklearn.svm import SVR
sr=SVR(kernel='rbf')
sr.fit(x_train, y_train)


/Users/muskangupta/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [8]:
#predict
y_pred=sr.predict(ss_x.transform(x_test))
print(y_pred)
y_pred=y_pred.reshape(-1,1)
print(y_pred)
print(y_test)

[-1.18727339  0.21311322  0.39445405 ...  0.9556216  -0.87278266
  0.38779571]
[[-1.18727339]
 [ 0.21311322]
 [ 0.39445405]
 ...
 [ 0.9556216 ]
 [-0.87278266]
 [ 0.38779571]]
[[431.23]
 [460.01]
 [461.14]
 ...
 [473.26]
 [438.  ]
 [463.28]]


In [11]:
y_pred=ss_y.inverse_transform(y_pred)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(-1,1),y_test.reshape(-1,1)),1))

[[7857.71 7809.57]
 [8265.12 8300.46]
 [8317.87 8319.73]
 ...
 [8481.13 8526.46]
 [7949.2  7925.04]
 [8315.94 8356.23]]


In [12]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.948078404998626